version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: forum-mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - forum-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forum-app
    depends_on:
      - mysql
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://forum-mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - forum-network

networks:
  forum-network:
